### ISSUE TITLE
Translate on pageload

### ISSUE THREAD

**Issue by DylanMeeus** [drshrey/alpharabius#1]
Instead of having to click on the "translate" button, it would be nice if the translation was applied automatically when the page loads.

**Comment by drshrey** [comment]
Yeah, good point. It seems like it's happening only sometimes (when on button is already there and a page been translated already in the current session). Thanks, will address.

**Comment by drshrey** [comment]
Addressed the issue here: https://github.com/drshrey/alpharabius/commit/41de5c339dd1fff98823e23cd8af1123685cf24d . You should be able to translate on page load as well as persist all preferences dynamically to all open tabs in all open windows 😄
